### ISSUE TITLE
Error while building php-fpm container

### ISSUE THREAD

**Issue by eleftrik** [ceronem/laravel-compose#2]
After launching `./start`, while building php-fpm container I got this error:

```
configure: error: unrecognized options: --enable-gd-native-ttf
ERROR: Service 'php-fpm' failed to build: The command '/bin/sh -c docker-php-ext-configure gd         --enable-gd-native-ttf         --with-jpeg-dir=/usr/lib         --with-freetype-dir=/usr/include/freetype2 &&     docker-php-ext-install gd' returned a non-zero code: 1
```

Thank you!

**Comment by ceronem** [comment]
fix https://github.com/ceronem/laravel-compose/tree/b91ec8acb1c2a194035118703b2b41f3cea8fc68

**Comment by ceronem** [comment]
@eleftrik fixed [commit](https://github.com/ceronem/laravel-compose/tree/b91ec8acb1c2a194035118703b2b41f3cea8fc68)
